<a href="https://colab.research.google.com/github/Sheila-otuko/machine_learning_practice/blob/main/sklearn_Multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
path = '/content/drive/MyDrive/1.02. Multiple linear regression.csv'
data = (path)

In [7]:
data = pd.read_csv(path)
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [8]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

create the multiple linear regression

In [14]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [15]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [18]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [19]:
reg.intercept_

0.29603261264909486

calculating r squared

In [20]:
reg.score(x,y)

0.40668119528142843

formula for R-squared

R2 = 1 – [(1-R2)*(n-1)/(n-k-1)]

In [21]:
x.shape

(84, 2)

In [25]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1 - (1 - r2)*(n - 1)/(n - p - 1)
adjusted_r2

0.39203134825134023

Feature selection with F-regression

In [26]:
from sklearn.feature_selection import f_regression


In [28]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [29]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

p values are only useful if they are less than 0.05

In [30]:
p_values.round(3)

array([0.   , 0.676])

creating a summary table

In [34]:
reg_summary = pd.DataFrame(data = ['SAT', 'Rand 1,2,3'], columns=['Features'])
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Feautures'])
reg_summary

Feautures
0         SAT
1  Rand 1,2,3

In [36]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p_values'] = p_values.round(3)
reg_summary

Feautures  Coefficients  p_values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676