<a href="https://colab.research.google.com/github/Sheila-otuko/machine_learning_practice/blob/main/sklearn_test_train_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
from sklearn.model_selection import train_test_split

In [32]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

split the data

In [34]:
train_test_split(a)

[array([ 62,   4,  63, 100,  47,  35,  37,  91,  87,  51,  79,  31,  41,
         14,  36,  28,  81,  21,  69,  72,  26,  19,  33,  32,  29,  99,
         49,  92,   9,   8,  98,  78,  40,  10,  60,  44,  34,  68,  39,
         85,  20,  55,  80,  67,  15,  70,  45,  71,  57,  90,  25,  52,
         96,  65,  54,  97,  53,  86,  46,  48,  22,  42,  66,  18,  58,
         30,  61,  27,  82,  59,  16,  56,  88,  50,  13]),
 array([83, 94, 84,  3,  1,  2, 17, 74, 77, 93, 12, 38,  7, 89,  6, 75, 23,
        24, 73,  5, 76, 95, 11, 43, 64])]

In [35]:
a_train, a_test, b_train, b_test = train_test_split(a, b,test_size = 0.2, random_state=42 )#shuffle=False)
#test_size gives us an 80/20 split default is 75/25
#shuffle is set by default to true. setting it to false leaves the data unshuffled. useful in time series modelling
#random_state prevents the code creating a new shuffle everytime you run the code. if you want a different random set change the number.

In [36]:
train_test_split(a)

[array([ 93,  62,  59,  28,  21,   9,  85,  64,  11,  47,  45,  57,  25,
         37,  63,  49,  48,  80,  77,  68,  16,  31,  69,  90,  71,  27,
         99,  92,  40,  52,  89,  22,   1,  75,  51,   4,  78,  24,  81,
         87,  61,  79,  83,  72,  66,   3,  94,  15,  65,  84,  38,  96,
         20,  88,  30,  36,   2,  42,  56, 100,  70,  54,  39,   8,  95,
         73,  44,  50,  97,  23,  29,  60,  12,   7,  46]),
 array([19, 41, 58, 82,  5, 74, 34, 53, 26, 91,  6, 18, 14, 86, 67, 43, 35,
        33, 32, 98, 17, 76, 55, 10, 13])]

In [37]:
a_train.shape, a_test.shape

((80,), (20,))

In [38]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [39]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [30]:
b_train.shape, b_test.shape

((80,), (20,))

In [40]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [41]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])